set(ISA_C_FLAGS "-std=gnu99 -ffreestanding -Wall -Wextra -Werror=return-type -Wno-unused-parameter -fno-exceptions -mno-red-zone -mgeneral-regs-only ")
set(ISA_CPP_FLAGS "-std=c++17 -ffreestanding -Wall -Wextra -Wno-unused-parameter -fno-exceptions -mno-red-zone -mgeneral-regs-only -fno-rtti")
set(ISA_ASM_FLAGS "-ffreestanding -Wall -Wextra -Wno-unused-parameter -fno-exceptions -mno-red-zone -mgeneral-regs-only -x assembler-with-cpp")
set(ISA_LINKER_FLAGS "-ffreestanding -nostdlib")

if(CMAKE_BUILD_TYPE MATCHES RelWithDebInfo)
    set(ISA_C_FLAGS "${ISA_C_FLAGS} -O3 -g")
    set(ISA_CPP_FLAGS "${ISA_CPP_FLAGS} -O3 -g")
    set(ISA_ASM_FLAGS "${ISA_ASM_FLAGS} -O3 -g")
    set(ISA_LINKER_FLAGS "${ISA_LINKER_FLAGS} -O3 -g")
elseif(CMAKE_BUILD_TYPE MATCHES Debug)
    set(ISA_C_FLAGS "${ISA_C_FLAGS} -O0 -g")
    set(ISA_CPP_FLAGS "${ISA_CPP_FLAGS} -O0 -g")
    set(ISA_ASM_FLAGS "${ISA_ASM_FLAGS} -O0 -g")
    set(ISA_LINKER_FLAGS "${ISA_LINKER_FLAGS} -O0 -g")
else()
    set(ISA_C_FLAGS "${ISA_C_FLAGS} -O3")
    set(ISA_CPP_FLAGS "${ISA_CPP_FLAGS} -O3")
    set(ISA_ASM_FLAGS "${ISA_ASM_FLAGS} -O3")
    set(ISA_LINKER_FLAGS "${ISA_LINKER_FLAGS} -O3")
endif()